In [18]:
import pandas as pd

In [19]:
df1 = pd.read_csv("/Users/ianbyrne/Development/CapstoneTeamJim/notebooks/ian-scratchpads/Data/monthly2020_pytorch_targets.csv")

In [26]:
df1.head()

,Unnamed: 0,county_fips,region,state,property_type,month,target
0,0,10001,"Kent County, DE",Delaware,All Residential,0,225000.0
1,1,10001,"Kent County, DE",Delaware,Condo/Co-op,0,50000.0
2,2,10001,"Kent County, DE",Delaware,Single Family Residential,0,235000.0
3,3,10001,"Kent County, DE",Delaware,Townhouse,0,158500.0
4,4,10003,"New Castle County, DE",Delaware,All Residential,0,229000.0

In [21]:
df2 = pd.read_csv("/Users/ianbyrne/Development/CapstoneTeamJim/notebooks/ian-scratchpads/Data/monthly2020_pytorch_diff.csv")
df2.rename(columns={"target": "diff"}, inplace=True)

In [22]:
df2.head()

,Unnamed: 0,county_fips,region,state,property_type,month,diff
0,0,10001,"Kent County, DE",Delaware,All Residential,0,270.26562
1,1,10001,"Kent County, DE",Delaware,Condo/Co-op,0,-33141.86000
2,2,10001,"Kent County, DE",Delaware,Single Family Residential,0,-6.34375
3,3,10001,"Kent County, DE",Delaware,Townhouse,0,-20595.48400
4,4,10003,"New Castle County, DE",Delaware,All Residential,0,-7545.71880

In [28]:
df2["target"] = df1["target"]

In [29]:
df2["preds"] = df2["target"] - df2["diff"]

In [30]:
df2

,Unnamed: 0,county_fips,region,state,property_type,month,diff,target,preds
0,0,10001,"Kent County, DE",Delaware,All Residential,0,270.26562,225000.0,224729.73438
1,1,10001,"Kent County, DE",Delaware,Condo/Co-op,0,-33141.86000,50000.0,83141.86000
2,2,10001,"Kent County, DE",Delaware,Single Family Residential,0,-6.34375,235000.0,235006.34375
3,3,10001,"Kent County, DE",Delaware,Townhouse,0,-20595.48400,158500.0,179095.48400
4,4,10003,"New Castle County, DE",Delaware,All Residential,0,-7545.71880,229000.0,236545.71880
...,...,...,...,...,...,...,...,...,...
54739,54739,9013,"Tolland County, CT",Connecticut,Single Family Residential,11,22882.78100,260000.0,237117.21900
54740,54740,9015,"Windham County, CT",Connecticut,All Residential,11,18437.79700,225000.0,206562.20300
54741,54741,9015,"Windham County, CT",Connecticut,Condo/Co-op,11,20881.78100,198000.0,177118.21900
54742,54742,9015,"Windham County, CT",Connecticut,Multi-Family (2-4 Unit),11,21185.29700,183000.0,161814.70300
54743,54743,9015,"Windham County, CT",Connecticut,Single Family Residential,11,18492.28100,234000.0,215507.71900

In [31]:
df2.drop(columns="Unnamed: 0", inplace=True)

In [37]:
df2 = df2[df2["property_type"] == "All Residential"]

In [38]:
df2.sort_values(by="diff", key=abs)

,county_fips,region,state,property_type,month,diff,target,preds
21660,48459,"Upshur County, TX",Texas,All Residential,4,0.0,85000.0,85000.0
17098,48459,"Upshur County, TX",Texas,All Residential,3,0.0,85000.0,85000.0
30784,48459,"Upshur County, TX",Texas,All Residential,6,0.0,85000.0,85000.0
26222,48459,"Upshur County, TX",Texas,All Residential,5,0.0,85000.0,85000.0
7974,48459,"Upshur County, TX",Texas,All Residential,1,0.0,85000.0,85000.0
...,...,...,...,...,...,...,...,...
30585,48035,"Bosque County, TX",Texas,All Residential,6,2092763.1,2250000.0,157236.9
26023,48035,"Bosque County, TX",Texas,All Residential,5,2094221.9,2250000.0,155778.1
21461,48035,"Bosque County, TX",Texas,All Residential,4,2095878.9,2250000.0,154121.1
16899,48035,"Bosque County, TX",Texas,All Residential,3,2097707.5,2250000.0,152292.5
51822,28063,"Jefferson County, MS",Mississippi,All Residential,11,2215215.0,2230000.0,14785.0

In [64]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17628 entries, 0 to 54740
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   county_fips    17628 non-null  int64
 1   region         17628 non-null  object
 2   state          17628 non-null  object
 3   property_type  17628 non-null  object
 4   month          17628 non-null  int64
 5   diff           17628 non-null  float64
 6   target         17628 non-null  float64
 7   preds          17628 non-null  float64
dtypes: float64(3), int64(2), object(3)
memory usage: 1.2+ MB

In [14]:
#df2.rename(columns={"target-prediction": "diff"}, inplace=True)

In [39]:
df2.to_csv("pytorch_monthly2020_preds.csv")

In [43]:
data = pd.read_csv(
    "/Users/ianbyrne/Development/CapstoneTeamJim/notebooks/ian-scratchpads/Data/nn_monthly_data.csv.gz",
    parse_dates=["period_begin", "period_end"],
)
# add time index
data["time_idx"] = data["period_end"].dt.year * 12 + data["period_end"].dt.month
data["time_idx"] -= data["time_idx"].min()
data["month"] = data["period_end"].dt.month.astype(str).astype("category")

In [44]:
data.head()

,county_fips,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,...,fips,year,state_y,state_fips,income_tax_low,income_tax_high,corp_income_tax_low,corp_income_tax_high,time_idx,month
0,8014,2012-04-01,2012-04-30,30,county,5,368,f,"Broomfield County, CO",0,...,8,2012,COLORADO,8,4.63,4.63,4.63,4.63,3,4
1,8023,2012-04-01,2012-04-30,30,county,5,373,f,"Costilla County, CO",0,...,8,2012,COLORADO,8,4.63,4.63,4.63,4.63,3,4
2,8103,2012-04-01,2012-04-30,30,county,5,413,f,"Rio Blanco County, CO",0,...,8,2012,COLORADO,8,4.63,4.63,4.63,4.63,3,4
3,8069,2012-04-01,2012-04-30,30,county,5,396,f,"Larimer County, CO",0,...,8,2012,COLORADO,8,4.63,4.63,4.63,4.63,3,4
4,8059,2012-04-01,2012-04-30,30,county,5,391,f,"Jefferson County, CO",0,...,8,2012,COLORADO,8,4.63,4.63,4.63,4.63,3,4

In [65]:
#data.info()

In [66]:
train19 = data[(data["year"] == 2019) & (data["month"] == "11")]
preds20 = df2[(df2["month"]== 11)]

In [69]:
train19 = train19[["county_fips", "region", "state", "property_type", "month", "median_sale_price"]]

In [72]:
train19 = train19[train19["property_type"] == "All Residential"]

In [76]:
train19["month"] = train19["month"].astype("int")

/var/folders/2c/s645y52s5t71kcvd2nh21ntw0000gn/T/ipykernel_92987/1632082079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train19["month"] = train19["month"].astype("int")

In [77]:
train19.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1547 entries, 9939 to 562167
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   county_fips        1547 non-null   int64
 1   region             1547 non-null   object
 2   state              1547 non-null   object
 3   property_type      1547 non-null   object
 4   month              1547 non-null   int64
 5   median_sale_price  1547 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 84.6+ KB

In [78]:
preds20.info

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1469 entries, 50182 to 54740
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   county_fips    1469 non-null   int64
 1   region         1469 non-null   object
 2   state          1469 non-null   object
 3   property_type  1469 non-null   object
 4   month          1469 non-null   int64
 5   diff           1469 non-null   float64
 6   target         1469 non-null   float64
 7   preds          1469 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 103.3+ KB

In [79]:
df = pd.merge(preds20, train19, how="left")

In [88]:
df.rename(columns={"median_sale_price": "target19"}, inplace=True)

In [89]:
df

,county_fips,region,state,property_type,month,diff,target,preds,target19
0,10001,"Kent County, DE",Delaware,All Residential,11,18380.0940,252500.0,234119.9060,229900.0
1,10003,"New Castle County, DE",Delaware,All Residential,11,25619.4060,270000.0,244380.5940,243258.5
2,1007,"Bibb County, AL",Alabama,All Residential,11,87483.2660,226000.0,138516.7340,82555.0
3,1009,"Blount County, AL",Alabama,All Residential,11,7537.4062,171000.0,163462.5938,152450.0
4,1015,"Calhoun County, AL",Alabama,All Residential,11,15679.7030,145450.0,129770.2970,122000.0
...,...,...,...,...,...,...,...,...,...
1464,9007,"Middlesex County, CT",Connecticut,All Residential,11,29542.0310,299000.0,269457.9690,274800.0
1465,9009,"New Haven County, CT",Connecticut,All Residential,11,20280.7500,250000.0,229719.2500,210000.0
1466,9011,"New London County, CT",Connecticut,All Residential,11,26307.2190,259950.0,233642.7810,228500.0
1467,9013,"Tolland County, CT",Connecticut,All Residential,11,24481.8440,250000.0,225518.1560,212450.0
1468,9015,"Windham County, CT",Connecticut,All Residential,11,18437.7970,225000.0,206562.2030,210000.0

In [90]:
df["2019to2020increase"] = (df.preds - df.target19)/df.target19

In [98]:
df = df.sort_values(by="2019to2020increase", ascending=False)

In [96]:
f = open("/Users/ianbyrne/Development/CapstoneTeamJim/streamlit/data/VAR_counties.txt", "r")
content = f.read()
counties = content.split("\n")
f.close()

In [108]:
var = [int(i) for i in counties[1:-1]]

In [111]:
final2020 = df[df["county_fips"].isin(var)]

In [115]:
final2020[:10].to_csv("tft_top10_2020.csv")